### PR TITLE
Fix ModuleNotFoundError: No module named 'src'

### LINKED ISSUE #7: ModuleNotFoundError: No module named 'src'
```
maxwoolf$ sudo python3 src/generate_unconditional_samples.py
Traceback (most recent call last):
  File "src/generate_unconditional_samples.py", line 9, in <module>
    from src import model, sample, encoder
ModuleNotFoundError: No module named 'src'
```
Python can't import from a subfolder unless it's on the Python path.

### PR DESCRIPTION
**Pull request by GitHub30**
fix #7

### CODE REVIEW

**Comment by minimaxir** [comment]
LGTM

**Comment by WuTheFWasThat** [comment]
could you do the same in the interactive_conditional_samples.py script?

**Comment by GitHub30** [comment]
@WuTheFWasThat 
I fixed the same in the interactive_conditional_samples.py. It works.

**Comment by uptownnickbrown** [comment]
Just thought I'd mention I hit the same bug when running `interactive_conditional_samples.py` after initially pulling the repo, and made the same fix to address it.

**Comment by WuTheFWasThat** [comment]
@GitHub30 I just added a LICENSE (https://github.com/openai/gpt-2/issues/10) - do you agree to license your contribution under the MIT license?  Thanks!

**Pull request merged**
