### PR TITLE
Better example parameters for conditional sample command

### PR DESCRIPTION
**Pull request by imgntn**
This PR adds better initial parameters to the example conditional sample generation command in the docs.

The results are pretty poor in the interactive script with the default settings.  

Now, you'll get better results if you run the interactive samples using the example command from the README.

### CODE REVIEW

**Comment by WuTheFWasThat** [comment]
hi @imgntn!  Note the results do also depend a bit on the sorts of prompts you give it.  I do worry that `--top_k 40 --temperature 0.7` causes too much repetition, but we haven't experimented too much.  How does it compare to just `--top_k 40` only?  That's generally been our default

**Comment by imgntn** [comment]
Leaving off the temperature parameter works for me - temperature would still be at default of 1, 

I think that the main problem is that the ```top_k=0``` in the defaults, which is pretty rough if you just run the ```python3 src/interactive_conditional_samples.py``` command as is.  including ```top_k=40``` in the example command provides much better results.  

Not proposing changing the actual defaults, just what the README example is.  

For prompts, I used the Unicorn one from the blog as a baseline.


# top_k = 0
```
Model prompt >>> In a shocking finding, scientist discovered a herd of unicorns living in a remote, previously unexplored valley, in the Andes Mountains. Even more surprising to the researchers was the fact that the unicorns spoke perfect English.
======================================== SAMPLE 1 ========================================
 The Unicorn Trope Toilers drink alcohol and may avoid alcohol if they dont know the pronunciation of some dialects and swear. Because unicorns have an off tongue ll, they may hang people from a balcony whilst they enact slobber on unsuspecting people while riding their expensive bikes. Once the cul de sac banned the hunt, it was revealed that unicorns use their native tongue so they can't just polish his castellan clit also known as limp. Because limp doesnt understand english before it hatch smashes them like butter<|endoftext|>Manreach can optionally

authenticate with env # Now ecryptfs can optionally authenticate with SSH #

Manreach can optionally

authenticate because it also accepts

A trusted authenticated server: localhostname , prevailhostname , wudefyoubserveraccessheight , wudelabndadc , metatap Api settings, pandas HTTP request/response headers if the request is internal or international the server may request a legit: nonauthenticate abc limited to: smallpages , mac , ip

Accept: cookies only for: e1:4 : username not inherited or reported An exception is raised if the printer creation file is unavailable. If there is already a defender when this happens — execute The file header is not using.

A trusted authenticated server: localhostname , prevailhostname , wudefyoubserveraccessheight , wudelabndadc , metatap Api settings, pandas HTTP request/response headers if the request is internal or international the server may request a legit: nonauthenticate Abc restricted to: smallpages , mac , ip

Accept: cookies only for: e1:4 : username not inherited or reported An exception is raised if the printer creation file is unavailable. If there is already a defender when this happens — execute The file header is not using.

1.2.3.1: Calling SetException

inspectFormat appears to be called at Met3xx_7._19.1_block_iosvt3_sysmotive_TYL_PendingList. env: onError,`envCode176' is the program other symbols globline at Met3xx_7._19.2_block_iosvt3_sysmotive_TYL_PendingList. [...] 2, 2 ...met3xx_7.2_block_iosvt3_sysmotive_TYL_PendingList
================================================================================
```

# top_k = 40

```
Model prompt >>> In a shocking finding, scientist discovered a herd of unicorns living in a remote, previously unexplored valley, in the Andes Mountains. Even more surprising to the researchers was the fact that the unicorns spoke perfect English.

======================================== SAMPLE 1 ========================================


"To understand the behavior of the animals and their habitat, we have to take into account their evolutionary history, their physical environment, and their dietary habits," lead researcher Dr. Thomas S. Sauer of the University of Hawaii told The Guardian. "This also may indicate how humans evolved. Humans are always different from other animals, including our own species who have evolved similar adaptations for the same purpose."

What's more, an article in an online peer-reviewed journal is "very exciting to understand", notes Sauer. "As well as our understanding of the physical environment, we are also working to understand the biology of the animals and their lifestyle, e.g. why their behaviours are different from ours."

While the researchers' findings are not surprising, their findings are particularly relevant to their work in California, which has a state biodiversity advisory panel with a strong focus on protecting endangered species in its area.<|endoftext|>Image copyright AP Image caption The first US president ever to visit Venezuela

After a failed presidential campaign, President Nicolas Maduro says he is ready to return to the country of his birth in the future.

But not before he gives the Venezuelan word: "I am a father".

Despite a tumultuous past, there were signs for President Maduro at the time he gave his term.

More than 30 people were killed and thousands injured in violence during the 2011 anti-government protests in Caracas.

He was assassinated last year, and more than 30 were injured in attacks on political rivals in recent months.

Despite his many political failures, there were signs that he was finally ready to break out of the shadow of his predecessor Hugo Chavez and restore order.

Image copyright Reuters Image caption Mr Maduro's wife, Carla, had given birth to their daughter in the state where she now lives

The last time there was such a rapid release of new government ministers was in 2002. President Maduro had been in power for only seven years as well as 15 before having to step down following protests in the streets.

He had also been in power for 10 years before Chavez was overthrown in a May 2013 coup.

Mr Maduro says his political transformation is not the start of a road to democracy.

"We have to change our laws to serve as an answer to the power struggle."

He said government reforms had not been implemented despite the mass protests over the protests in Caracas.

'More than 200,000 children and grandchildren'

He says
```

**Comment by WuTheFWasThat** [comment]
@imgntn I just added a LICENSE (https://github.com/openai/gpt-2/issues/10) - do you agree to license your contribution under the MIT license?  Thanks!

**Comment by imgntn** [comment]
Yes, I agree.  Thanks!

**Pull request merged**
